### ISSUE TITLE
Will this ever come back to MonoDevelop?

### ISSUE THREAD

**Issue by flaub** [mhutch/cbinding#8]
What would it take to integrate it back into the latest MonoDevelop? I see that MonoDevelop 6 dropped support for this addin with https://github.com/mono/monodevelop/commit/792f48882e650ac76cde4107211e644845895d6a

If you need contributions, I'm willing to spend some time on it since it's pretty critical that I can have C and C# projects together.

**Comment by VOM7HC** [comment]
If someone want to interop C# with C++, @mhutch answered here: https://stackoverflow.com/questions/15057041/get-c-c-project-support-back-with-monodevelop-4-0-a-k-a-xamarin-studio
Then, is there any new infomations when it will be interagted in Visual Studio for Mac and MonoDevelop again, @mhutch??
